[package]
name = "flappy-bird"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = { version = "0.4.4", features = ["audio"] }

[package.metadata.android.activity_attributes]
"android:exported" = "true"
